basePath: localhost:8080/
definitions:
  HTTPError:
    properties:
      message:
        example: error message
        type: string
    type: object
  TodoElement:
    properties:
      id:
        example: 1
        type: integer
    type: object
info:
  contact: {}
  description: This is Atplace server.
  license:
    name: Atplace
  title: Atplace API
paths:
  /v1/todos/details:
    get:
      description: TODO ID のリストを受け取って、それらの情報を返すエンドポイント
      operationId: Details
      parameters:
      - description: todo_ids
        in: query
        name: todo_ids
        required: true
        type: array
      - description: X-API-TOKEN
        in: header
        name: X-API-TOKEN
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/TodoElement'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/HTTPError'
      summary: TODO リストを返すエンドポイント
swagger: "2.0"
